name: hod_speech_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.4
  coast_audio: ^0.0.5
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  just_waveform: ^0.0.5
  mic_stream: ^0.7.1+2
  permission_handler: ^11.3.0
  record: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
